version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "sqlite:///app/database.db"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: "nouchka/sqlite3"
    volumes:
      - sqlite_data:/app

volumes:
  sqlite_data:
