	CREATE TABLE IF NOT EXISTS comments (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		post_id INTEGER NOT NULL,
		username TEXT NOT NULL,
		content TEXT NOT NULL,
		img BLOB,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);